[versions]
sqliteJdbc = "3.53.4.0"
jlayer = "1.0.1"
junit = "5.10.1"
mockito = "5.24.0"
mockitoCompile = "5.24.0"
jetbrainsAnnotations = "24.0.1"
kotlin = "2.2.0"
composeMultiplatform = "1.8.2"
spotbugsPlugin = "6.5.12"
spotbugs = "4.9.8"
pmd = "7.17.0"

[libraries]
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqliteJdbc" }
jlayer = { module = "javazoom:jlayer", version.ref = "jlayer" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
mockito-core-compile = { module = "org.mockito:mockito-core", version.ref = "mockitoCompile" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugsPlugin" }
